apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-helloworld
  template:
    metadata:
      labels:
        app: demo-helloworld
    spec:
      containers:
        - name: app
          image: vishal4590/demo-helloworld:2.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
